domain_path: /home/yian/project/FPGA/diansai/backup/p1_2025_G_fx/vitis/platform0/export/platform0/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
