set_property IOB TRUE [all_inputs]
set_property IOB TRUE [all_outputs]
# 200M差分时钟
set_property PACKAGE_PIN F9 [get_ports CLK_IN1_D_clk_p]
set_property IOSTANDARD DIFF_SSTL135 [get_ports CLK_IN1_D_clk_p]
create_clock -period 5.000 -name sysclk_i -add [get_ports CLK_IN1_D_clk_p]

set_property PACKAGE_PIN Y23 [get_ports power_en]
set_property IOSTANDARD LVCMOS33 [get_ports power_en]

set_property PACKAGE_PIN Y28 [get_ports dac_frame_p]
# set_property PACKAGE_PIN AA29 [get_ports dac_frame_n]
# set_property IOSTANDARD LVCMOS25 [get_ports dac_frame_n]
set_property IOSTANDARD LVDS_25 [get_ports dac_frame_p]
# 时钟
set_property PACKAGE_PIN AD18 [get_ports input_clk_50M]
set_property IOSTANDARD LVCMOS33 [get_ports input_clk_50M]

# 100M左右
set_property PACKAGE_PIN U26 [get_ports adc_dco_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports adc_dco_clk_p]
create_clock -period 10 -name adc_dco_clk_p -add [get_ports adc_dco_clk_p]

set_property PACKAGE_PIN V28 [get_ports dac_dci_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports dac_dci_clk_p]
# SPI
set_property PACKAGE_PIN P30 [get_ports fmc_spi_sclk]
set_property PACKAGE_PIN R30 [get_ports fmc_spi_sdio]
set_property IOSTANDARD LVCMOS25 [get_ports fmc_spi_sclk]
set_property IOSTANDARD LVCMOS25 [get_ports fmc_spi_sdio]

set_property PACKAGE_PIN AD28 [get_ports fmc_clk_cs]
set_property IOSTANDARD LVCMOS25 [get_ports fmc_clk_cs]
set_property PACKAGE_PIN AC28 [get_ports fmc_adc_cs]
set_property IOSTANDARD LVCMOS25 [get_ports fmc_adc_cs]
set_property PACKAGE_PIN N29 [get_ports fmc_dac_cs]
set_property IOSTANDARD LVCMOS25 [get_ports fmc_dac_cs]
#ADC_DATA
set_property PACKAGE_PIN AB27 [get_ports {adc_in_v_p[0]}]
set_property PACKAGE_PIN AF30 [get_ports {adc_in_v_p[1]}]
set_property PACKAGE_PIN U25 [get_ports {adc_in_v_p[2]}]
set_property PACKAGE_PIN AK27 [get_ports {adc_in_v_p[3]}]
set_property PACKAGE_PIN AJ30 [get_ports {adc_in_v_p[4]}]
set_property PACKAGE_PIN AG26 [get_ports {adc_in_v_p[5]}]
set_property PACKAGE_PIN AJ28 [get_ports {adc_in_v_p[6]}]
set_property PACKAGE_PIN AH26 [get_ports {adc_in_v_p[7]}]
set_property PACKAGE_PIN AE27 [get_ports {adc_in_v_p[8]}]
set_property PACKAGE_PIN AF29 [get_ports {adc_in_v_p[9]}]
set_property PACKAGE_PIN AC26 [get_ports {adc_in_v_p[10]}]
set_property PACKAGE_PIN AD30 [get_ports {adc_in_v_p[11]}]
set_property PACKAGE_PIN AB29 [get_ports {adc_in_v_p[12]}]
set_property PACKAGE_PIN AE25 [get_ports {adc_in_v_p[13]}]
set_property -dict {IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {adc_in_v_p[*]}]
#DAC_DATA
set_property PACKAGE_PIN N28 [get_ports {dac_out_v_p[0]}]
set_property PACKAGE_PIN P25 [get_ports {dac_out_v_p[1]}]
set_property PACKAGE_PIN N26 [get_ports {dac_out_v_p[2]}]
set_property PACKAGE_PIN P23 [get_ports {dac_out_v_p[3]}]
set_property PACKAGE_PIN T29 [get_ports {dac_out_v_p[4]}]
set_property PACKAGE_PIN R27 [get_ports {dac_out_v_p[5]}]
set_property PACKAGE_PIN T30 [get_ports {dac_out_v_p[6]}]
set_property PACKAGE_PIN T24 [get_ports {dac_out_v_p[7]}]
set_property PACKAGE_PIN V27 [get_ports {dac_out_v_p[8]}]
set_property PACKAGE_PIN W25 [get_ports {dac_out_v_p[9]}]
set_property PACKAGE_PIN W29 [get_ports {dac_out_v_p[10]}]
set_property PACKAGE_PIN Y30 [get_ports {dac_out_v_p[11]}]
set_property PACKAGE_PIN AE28 [get_ports {dac_out_v_p[12]}]
set_property PACKAGE_PIN R25 [get_ports {dac_out_v_p[13]}]
set_property PACKAGE_PIN AA27 [get_ports {dac_out_v_p[14]}]
set_property PACKAGE_PIN Y26 [get_ports {dac_out_v_p[15]}]
set_property -dict {IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {dac_out_v_p[*]}]

# 调试串口
# set_property PACKAGE_PIN AC12 [get_ports UART_0_rxd]
# set_property IOSTANDARD LVCMOS33 [get_ports UART_0_rxd]
# set_property PACKAGE_PIN AB12 [get_ports UART_0_txd]
# set_property IOSTANDARD LVCMOS33 [get_ports UART_0_txd]
# 控制串口
set_property PACKAGE_PIN AJ16 [get_ports UART_1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_rxd]
set_property PACKAGE_PIN AK16 [get_ports UART_1_txd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_txd]
# 继电器
set_property PACKAGE_PIN AB12 [get_ports o_jidianqi]
set_property IOSTANDARD LVCMOS33 [get_ports o_jidianqi]